version: '3'
services:
  # app:
  #   image: node:16
  #   volumes:
  #     - ./:/app
  #   command: npm run start
  #   ports:
  #     - "3000:3000"
  #     - "10000-20000:10000-20000/udp"
  #   environment:
  #     - NODE_ENV=production
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./hls_output:/usr/share/nginx/html/hls
    ports:
      - "8080:8080"